cli:   "bitrot-scanner"
group: "bitrot-scanner"
user:  "bitrot-scanner"

targets:
  centos-6:
  centos-7:
  debian-7:
  debian-8:
  sles-12:
  ubuntu-12.04:
  ubuntu-14.04:
  ubuntu-16.04:

after:
  - rm -rvf Godeps vendor *.go .profile.d
